### ISSUE TITLE
some signatures that have been suppressed by RefSeq/GenBank are not in wort

### ISSUE THREAD

**Issue by taylorreiter** [sourmash-bio/wort#37]
For example, the following accessions have been "suppressed" in RefSeq and GenBank, and do no appear in wort (`/group/ctbrowngrp/irber/data/wort-data/wort-genomes/sigs/<accession>.sig`). I checked newer version numbers and still did not find these accessions (e.g. `GCA_900474135*sig`). Looking on GenBank, I see the record has been suppressed/removed: https://www.ncbi.nlm.nih.gov/assembly/GCF_900474135.2/

```
GCA_900474135.2
GCA_002798115.1
GCA_001308105.1
```

I couldn't find why these records were removed, but thought I'd document this here!

**Comment by luizirber** [comment]
At some point I added the removed/suppressed assemblies (the `*_historical.txt` files in https://ftp.ncbi.nlm.nih.gov/genomes/ASSEMBLY_REPORTS/), and the three cases are available in wort now.
